### ISSUE TITLE
Serialize the Trie

### ISSUE THREAD

**Issue by roccomuso** [davedoesdev/qlobber#14]
Any way to serialize and export/import a built trie?

**Comment by davedoesdev** [comment]
Not yet. I don't want to build a particular serialization format into the trie. Rather, I was thinking of adding methods to import/export from a plain json object which the caller could then serialize (e.g. using JSON).

@roccomuso what do you think?

**Comment by roccomuso** [comment]
I mean JSON serialization is ok, but it requires a little bit more effort with the Maps structures, that's why can be useful to provide methods for that.
import/export would be great!

**Comment by davedoesdev** [comment]
Yep, import/export to standard Javascript object should be enough I think. Export will convert the Maps to objects and Sets to arrays. Import will go the other way. Does that sound right?

**Comment by roccomuso** [comment]
Cool, thanks!

**Comment by davedoesdev** [comment]
I'm going to think it over again. For large tries, serialising to a stream is probably best. There must be some Node serialisation modules out there to help.

**Comment by davedoesdev** [comment]
@roccomuso this is implemented in version 3.0.0.
Rather than add support for a specific serialization format into qlobber, I've instead added methods to [visit](https://github.com/davedoesdev/qlobber#qlobberprototypevisit) the trie and [restore](https://github.com/davedoesdev/qlobber#qlobberprototypeget_restoreroptions) the trie.

The objects you get from the visit iterator can be serialized and deserialized using JSON, for example.

There are also stream wrappers around these methods ([`VisitorStream`](https://github.com/davedoesdev/qlobber#visitorstreamqlobber) and [`RestorerStream`](https://github.com/davedoesdev/qlobber#restorerstreamqlobber).

For an example of how you might use these to serialize to and deserialize from JSON, see [this test](https://github.com/davedoesdev/qlobber/blob/master/test/json.js). It uses `VisitorStream` and `RestorerStream` in conjunction with [JSONStream](https://github.com/dominictarr/JSONStream).

**Comment by davedoesdev** [comment]
@roccomuso please give it a try and let me know how it goes.

**Comment by davedoesdev** [comment]
@roccomuso did you manage to test serialization?

**Comment by roccomuso** [comment]
yes, it works :) thanks
